name: getsentry Lint

on: pull_request

jobs:

    runs-on: ubuntu-latest
    steps:
        - name: Use current action
        uses: getsentry/action-eslint-fix@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}